### ISSUE TITLE
IOError: [Errno socket error] [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by jt-mick** [Hackuracy/zabbix-solr-multicore#2]
Hi,
I have some issue.

Traceback (most recent call last):
  File "./Solr-pypoll.py", line 26, in <module>
    main() 
  File "./Solr-pypoll.py", line 15, in main
    resp=urllib.urlopen(fqdn+uri).read()
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 345, in open_http
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] Connection timed out

and Zabbix server command

[root@XX-zabbix]# zabbix_get -s 10.5.XX.XX -p 10050 -k "solr.core.discovery"
ZBX_NOTSUPPORTED: Timeout while executing a shell script.

I look forward to hearing from you soon. Thank you.

**Comment by Hackuracy** [comment]
It sounds like a firewall issue or selinux misconfiguration
